### ISSUE TITLE
Remove all files under _site from repo?

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSB_homepage#19]
Are all the files under _site regenerated when deployed? I see the recent changes for 404 are only made on https://github.com/OpenSourceBrain/OSB_homepage/blob/main/_site/404.html, but others are clearly regenerated on deployment, e.g. https://github.com/OpenSourceBrain/OSB_homepage/blob/main/_site/index.html is out of date, but the pages gets regenerated properly. 

@filippomc

**Comment by filippomc** [comment]
agree that's generated and it's better git ignored. FYI the 404 source is here: https://github.com/OpenSourceBrain/OSB_homepage/blob/main/404.html
