### ISSUE TITLE
Add "Funded by Wellcome" to footer?

### ISSUE THREAD

**Issue by sanjayankur31** [OpenSourceBrain/OSB_homepage#32]
It'll be good to have "Funded by Wellcome" somewhere in the page---the footer, but maybe somewhere more prominent also if it fits?

**Comment by pgleeson** [comment]
Yep, on it...

**Comment by pgleeson** [comment]
Done in PR, though should prob link to a dedicated page on the main docs...

**Comment by pgleeson** [comment]
Page on funding is here. More (grant numbers etc) can be added... https://docs.opensourcebrain.org/General/Funding.html
