### ISSUE TITLE
Embed the video in the website

### ISSUE THREAD

**Issue by filippomc** [OpenSourceBrain/OSB_homepage#38]

**Comment by filippomc** [comment]
Design done: https://www.figma.com/file/mV8x58zpYzHUtPLFQdsU5F/OSB-Landing-Page?type=design&node-id=1456%3A136&mode=design&t=wjjjqkCNJmZ33X59-1


![Image](https://github.com/OpenSourceBrain/OSB_homepage/assets/46561561/aeb5c378-e766-4eac-9c84-ee18ef8710d0)

**Comment by filippomc** [comment]
Added some notes in the figma, can proceed with the implementation. Need a web optimized version

**Comment by filippomc** [comment]
8MB video for embedding:
https://github.com/OpenSourceBrain/OSB_homepage/assets/46561561/a5d738a3-e495-4c67-8608-3b3d42077c54

**Comment by filippomc** [comment]
replace the image of the website with the new version

**Comment by filippomc** [comment]
A highe resolution version of the video

https://github.com/OpenSourceBrain/OSB_homepage/assets/46561561/1df4ef97-0ea3-4093-b44a-45189b8d441d

**Comment by pgleeson** [comment]
Embedded. Tweaked so it doesn't autoplay and people think: who's that old bloke looking at the sky..?

**Comment by pgleeson** [comment]
Done
