### ISSUE TITLE
Homepage looks darker on Firefox compared to Chrome

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/OSB_homepage#6]
Firefox on left, Chrome on right, this is on Mac, seeing similar on Linux

<img width="1716" alt="Screenshot 2023-02-16 at 17 15 15" src="https://user-images.githubusercontent.com/1556687/219439265-d501cd3a-0cb1-4290-b86d-f0dbae53c200.png">

**Comment by pgleeson** [comment]
@filippomc @Salam-Dalloul bumping this to 0.7.2.1 release as the homepage looks very dark and washed out on Firefox, and doesn't give a good impression to new users. It looks better on my laptop sscreen which is quite bright, but on other screens it's all quite dark. 

It would be better if it was tested across browsers and the graphical elements made a bit clearer.

**Comment by filippomc** [comment]
@Salam-Dalloul the issue is in the -webkit-mask-image usage, as it's applied to the header. It better to mask the image below only

**Comment by pgleeson** [comment]
Fixed now!
